# Generated by Django 4.2 on 2023-04-29 08:50

from django.db import migrations, models
import django.db.models.deletion
import social_media.models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_follow"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to=social_media.models.post_image_file_path
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="social_media.profile",
                    ),
                ),
            ],
        ),
    ]
